// Generated by dia2code
#ifndef STATE__ADJACENCIES__H
#define STATE__ADJACENCIES__H

#include <string>
#include <map>

namespace state {

  /// class Adjacencies - 
  class Adjacencies {
    // Attributes
  private:
    std::map<std::string, std::map<std::string, int>> val;
    // Operations
  public:
    Adjacencies ();
    Adjacencies (std::string rawCsv);
    // Setters and Getters
  };

};

#endif
