// Generated by dia2code
#ifndef STATE__AIPLAYER__H
#define STATE__AIPLAYER__H


namespace state {

  /// class AIPlayer - 
  class AIPlayer {
    // Operations
  public:
    AIPlayer ();
    // Setters and Getters
  };

};

#endif
