// Generated by dia2code
#ifndef STATE__ARMY__H
#define STATE__ARMY__H

#include <string>
#include <vector>
#include <queue>

namespace state {
  class TravelOrder;
}

#include "TravelOrder.h"

namespace state {

  /// class Army - Class to describe a raised army on the map
  class Army {
    // Associations
    // Attributes
  private:
    std::string id;
    std::vector<std::string> levies;
    /// Pointer of the province where the army is currently located
    std::string currentProvince;
    std::string currentBattle;
    /// Queue of ongoing moving orders for the army
    static std::queue<TravelOrder> orders;
    // Operations
  public:
    Army ();
    // Setters and Getters
  };

};

#endif
