// Generated by dia2code
#ifndef STATE__BATTLE__H
#define STATE__BATTLE__H

#include <string>

namespace state {
  class Province;
  class Army;
}

#include "Province.h"
#include "Army.h"

namespace state {

  /// class Battle - A class describing an ongoing battle on the map
  class Battle {
    // Attributes
  private:
    std::string id;
    /// Location of the battle (pointer)
    IdRef<Province> province;
    IdRefList<Army> whiteArmies;
    IdRefList<Army> blackArmies;
    int startTurn;
    int endTurn;
    // Setters and Getters
  };

};

#endif
