// Generated by dia2code
#ifndef STATE__BATTLE__H
#define STATE__BATTLE__H

#include <string>
#include <vector>
#include <json.hpp>

namespace state {
  class GameMap;
}

namespace state {

  /// class Battle - A class describing an ongoing battle on the map
  class Battle {
    // Attributes
  private:
    GameMap * parent;
    std::string id;
    /// Location of the battle (pointer)
    std::string province;
    std::vector<std::string> whiteArmies;
    std::vector<std::string> blackArmies;
    int startTurn;
    int endTurn;
    // Operations
  public:
    Battle ();
    Battle (GameMap * parent, std::string strJson);
    ~Battle ();
    void setParent (GameMap * parent);
    bool checkConsistency ();
    void debug ();
    void advance ();
    std::string getProvince ();
    bool isFinished ();
    void close (int turn);
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
