// Generated by dia2code
#ifndef STATE__BATTLE__H
#define STATE__BATTLE__H

#include <string>

namespace state {

  /// class Battle - A class describing an ongoing battle on the map
  class Battle {
    // Attributes
  private:
    std::string id;
    /// Location of the battle (pointer)
    std::string province;
    std::string whiteArmies;
    std::string blackArmies;
    int startTurn;
    int endTurn;
    // Operations
  public:
    Battle ();
    // Setters and Getters
  };

};

#endif
