// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>
#include <vector>

namespace state {
  class Opinion;
  class Plot;
}

#include "Opinion.h"
#include "Plot.h"

namespace state {

  /// class Character - 
  class Character {
    // Associations
    // Attributes
  private:
    std::string name;
    std::string dynastyName;
    /// In turns number
    int age;
    std::vector<std::string> traits;
    std::vector<Opinion> opinions;
    int diplomacy;
    int stewardship;
    int martial;
    int intrigue;
    std::vector<std::string> claims;
    bool alive;
    int prestige;
    int gold;
    Plot currentPlot;
    // Operations
  public:
    Character ();
    // Setters and Getters
  };

};

#endif
