// Generated by dia2code
#ifndef STATE__CLAIMPLOT__H
#define STATE__CLAIMPLOT__H


namespace state {
  class Title;
  class Plot;
}

#include "Title.h"
#include "Plot.h"

namespace state {

  /// class ClaimPlot - 
  class ClaimPlot : public state::Plot {
    // Attributes
  private:
    IdRef<Title> targetTitle;
    // Setters and Getters
  };

};

#endif
