// Generated by dia2code
#ifndef STATE__CLAIMPLOT__H
#define STATE__CLAIMPLOT__H

#include <string>

namespace state {
  class Plot;
}

#include "Plot.h"

namespace state {

  /// class ClaimPlot - 
  class ClaimPlot : public state::Plot {
    // Attributes
  private:
    std::string targetTitle;
    // Operations
  public:
    ClaimPlot ();
    // Setters and Getters
  };

};

#endif
