// Generated by dia2code
#ifndef STATE__COUNTY__H
#define STATE__COUNTY__H

#include <string>

namespace state {
  class Title;
}

#include "Title.h"

namespace state {

  /// class County - A class inheriting from Title to describe a Count-level title
  class County : public state::Title {
    // Attributes
  private:
    /// Pointer to the related province
    std::string province;
    // Operations
  public:
    County ();
    // Setters and Getters
  };

};

#endif
