// Generated by dia2code
#ifndef STATE__COUNTY__H
#define STATE__COUNTY__H


namespace state {
  class Province;
  class Title;
}

#include "Province.h"
#include "Title.h"

namespace state {

  /// class County - A class inheriting from Title to describe a Count-level title
  class County : public state::Title {
    // Attributes
  private:
    /// Pointer to the related province
    IdRef<Province> province;
    // Setters and Getters
  };

};

#endif
