// Generated by dia2code
#ifndef STATE__DUCHY__H
#define STATE__DUCHY__H


namespace state {
  class Title;
}

#include "Title.h"

namespace state {

  /// class Duchy - 
  class Duchy : public state::Title {
    // Operations
  public:
    Duchy ();
    // Setters and Getters
  };

};

#endif
