// Generated by dia2code
#ifndef STATE__GAMESTATE__H
#define STATE__GAMESTATE__H

#include <state.h>
#include <vector>
#include <string>

namespace state {
  class Politics;
  class GameMap;
  class Ressources;
  class Player;
}

#include "Politics.h"
#include "GameMap.h"
#include "Ressources.h"
#include "Player.h"

namespace state {

  /// class GameState - A class describing the whole state of a game. Can be loaded and saved from a file.
  class GameState {
    // Associations
    // Attributes
  private:
    state::Politics politics;
    state::GameMap gameMap;
    state::Ressources ressources;
    std::vector<state::Player> players;
    unsigned int currentPlayer;
    int currentTurn;
    // Operations
  public:
    GameState ();
    GameState (const char* saveFilePath);
    GameState (const std::string saveFilePath);
    ~GameState ();
    void debug ();
    void setArmyOrder (std::string armyId, std::string destId);
    bool turnAdvance ();
    void updateArmiesOrders ();
    void checkNewBattles ();
    void updateBattles ();
    // Setters and Getters
  };

};

#endif
