// Generated by dia2code
#ifndef STATE__HUMANPLAYER__H
#define STATE__HUMANPLAYER__H


namespace state {

  /// class HumanPlayer - 
  class HumanPlayer {
    // Operations
  public:
    HumanPlayer ();
    // Setters and Getters
  };

};

#endif
