// Generated by dia2code
#ifndef STATE__IDREFLIST__H
#define STATE__IDREFLIST__H

#include <string>
#include <map>

namespace state {

  /// class IdRefList - 
  template <   T>
  class IdRefList {
    // Attributes
  private:
    std::map<std::string, * T> object;
    // Setters and Getters
  };

};

#endif
