// Generated by dia2code
#ifndef STATE__IDREF__H
#define STATE__IDREF__H

#include <string>

namespace state {

  /// class IdRef - 
  template <   T>
  class IdRef {
    // Attributes
  private:
    std::pair<std::string, * T> object;
    // Setters and Getters
  };

};

#endif
