// Generated by dia2code
#ifndef STATE__KINGDOM__H
#define STATE__KINGDOM__H

#include <string>
#include <json.hpp>

namespace state {

  /// class Kingdom - 
  class Kingdom {
    // Attributes
  private:
    std::string id;
    std::string name;
    std::string holder;
    unsigned int kingdomColorCode;
    // Operations
  public:
    Kingdom ();
    Kingdom (std::string strJson);
    ~Kingdom ();
    void debug ();
    bool checkConsistency ();
    unsigned int getColorCode ();
    std::string getHolder ();
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
