// Generated by dia2code
#ifndef STATE__KINGDOM__H
#define STATE__KINGDOM__H


namespace state {
  class Title;
}

#include "Title.h"

namespace state {

  /// class Kingdom - 
  class Kingdom : public state::Title {
    // Setters and Getters
  };

};

#endif
