// Generated by dia2code
#ifndef STATE__KINGDOM__H
#define STATE__KINGDOM__H

#include <string>

namespace state {
  class Title;
}

#include "Title.h"

namespace state {

  /// class Kingdom - 
  class Kingdom : public state::Title {
    // Operations
  public:
    Kingdom ();
    Kingdom (std::string strJson);
    ~Kingdom ();
    void debug ();
    bool checkConsistency ();
    std::string getLiege ();
    std::string getDeJureLiege ();
    // Setters and Getters
  };

};

#endif
