// Generated by dia2code
#ifndef STATE__LEVY__H
#define STATE__LEVY__H


namespace state {

  /// class Levy - A class representing the levies supported by a province
  class Levy {
    // Attributes
  private:
    /// Number of men in the levy
    int men;
    bool isRaised;
    /// Ranges from 0 (0%) to 150 (150%).
    float reinforcementRate;
    // Setters and Getters
  };

};

#endif
