// Generated by dia2code
#ifndef STATE__LEVY__H
#define STATE__LEVY__H

#include <string>

namespace state {

  /// class Levy - A class representing the levies supported by a province
  class Levy {
    // Attributes
  private:
    /// Number of men in the levy
    int men;
    bool isRaised;
    /// Ranges from 0 (0%) to 150 (150%).
    float reinforcementRate;
    // Operations
  public:
    Levy ();
    Levy (std::string strJson);
    ~Levy ();
    bool checkConsistency ();
    void debug ();
    int getMen ();
    void killMen (int victims);
    void disband ();
    // Setters and Getters
  };

};

#endif
