// Generated by dia2code
#ifndef STATE__LEVY__H
#define STATE__LEVY__H

#include <string>
#include <json.hpp>

namespace state {
  class Province;
}

namespace state {

  /// class Levy - A class representing the levies supported by a province
  class Levy {
    // Attributes
  private:
    /// Number of men in the levy
    int men;
    bool raised;
    /// Ranges from 0 (0%) to 150 (150%).
    float reinforcementRate;
    Province * parent;
    // Operations
  public:
    Levy ();
    Levy (Province * parent, std::string strJson);
    ~Levy ();
    bool checkConsistency ();
    void debug ();
    int getMen ();
    void killMen (int victims);
    void disband ();
    void update ();
    bool isRaised ();
    void setReinforcementRate (float rate);
    void reinforce (int men);
    float getReinforcementRate ();
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
