// Generated by dia2code
#ifndef STATE__MURDERPLOT__H
#define STATE__MURDERPLOT__H

#include <string>

namespace state {
  class Plot;
}

#include "Plot.h"

namespace state {

  /// class MurderPlot - 
  class MurderPlot : public state::Plot {
    // Attributes
  private:
    std::string targetCharacter;
    // Operations
  public:
    MurderPlot ();
    // Setters and Getters
  };

};

#endif
