// Generated by dia2code
#ifndef STATE__ONEPROVINCEORDER__H
#define STATE__ONEPROVINCEORDER__H


namespace state {
  class Order;
}

#include "Order.h"

namespace state {

  /// class OneProvinceOrder - A class describing a travel from one province to an adjacent province
  class OneProvinceOrder : public state::Order {
    // Setters and Getters
  };

};

#endif
