// Generated by dia2code
#ifndef STATE__ONEPROVINCEORDER__H
#define STATE__ONEPROVINCEORDER__H

#include <string>

namespace state {
  class Order;
}

#include "Order.h"

namespace state {

  /// class OneProvinceOrder - A class describing a travel from one province to an adjacent province
  class OneProvinceOrder : public state::Order {
    // Operations
  public:
    OneProvinceOrder ();
    OneProvinceOrder (std::string strJson);
    ~OneProvinceOrder ();
    bool checkConsistency ();
    void debug ();
    bool nextStep ();
    std::string getDestination ();
    // Setters and Getters
  };

};

#endif
