// Generated by dia2code
#ifndef STATE__OPINION__H
#define STATE__OPINION__H


namespace state {
  class Character;
};
class IdRef;
#include "Character.h"
#include "IdRef.h"

namespace state {

  /// class Opinion - 
  class Opinion {
    // Associations
    // Attributes
  private:
    IdRef<Character> target;
    int score;
    // Setters and Getters
  };

};

#endif
