// Generated by dia2code
#ifndef STATE__OPINION__H
#define STATE__OPINION__H

#include <string>

namespace state {

  /// class Opinion - 
  class Opinion {
    // Attributes
  private:
    std::string target;
    int score;
    // Operations
  public:
    Opinion ();
    // Setters and Getters
  };

};

#endif
