// Generated by dia2code
#ifndef STATE__ORDER__H
#define STATE__ORDER__H

#include <string>

namespace state {

  /// class Order - 
  class Order {
    // Attributes
  protected:
    std::string originProvinceId;
    std::string destinationProvinceId;
    /// Total number of turns necessary to execute the order
    int duration;
    /// Number of travel turns elapsed.
    int elapsed;
    // Operations
  public:
    virtual bool checkConsistency () = 0;
    virtual void debug () = 0;
    // Setters and Getters
    const std::string& getOriginProvinceId() const;
    void setOriginProvinceId(const std::string& originProvinceId);
    const std::string& getDestinationProvinceId() const;
    void setDestinationProvinceId(const std::string& destinationProvinceId);
    int getDuration() const;
    void setDuration(int duration);
    int getElapsed() const;
    void setElapsed(int elapsed);
  };

};

#endif
