// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <json.hpp>

namespace state {

  /// class Player - 
  class Player {
    // Attributes
  private:
    std::string id;
    std::string currentCharacter;
    int score;
    // Operations
  public:
    Player ();
    Player (nlohmann::json initJson);
    ~Player ();
    std::string getId ();
    std::string getCharacter ();
    void setCharacter (std::string newCharacterId);
    void addScore (int amount);
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
