// Generated by dia2code
#ifndef STATE__PLOT__H
#define STATE__PLOT__H


namespace state {

  /// class Plot - 
  class Plot {
    // Attributes
  private:
    int endTurn;
    // Setters and Getters
  };

};

#endif
