// Generated by dia2code
#ifndef STATE__POLITICS__H
#define STATE__POLITICS__H

#include <string>
#include <map>
#include <vector>

namespace state {
  class Relation;
  class Character;
  class Title;
}

#include "Relation.h"
#include "Character.h"
#include "Title.h"

namespace state {

  /// class Politics - 
  class Politics {
    // Associations
    // Attributes
  private:
    std::map<std::string, Title> titles;
    std::vector<Relation> relations;
    std::map<std::string, Character> characters;
    // Operations
  public:
    Politics ();
    // Setters and Getters
  };

};

#endif
