// Generated by dia2code
#ifndef STATE__RELATION__H
#define STATE__RELATION__H

#include <string>
#include <json.hpp>

namespace state {

  /// class Relation - 
  class Relation {
    // Attributes
  public:
    enum relType{non_aggression = 0, alliance = 1, friendship = 2, rivalry = 3, war = 4};
    /// Indicates war id if type is war
    std::string warId;
  private:
    std::string characterA;
    std::string characterB;
    relType type;
    int endTurn;
    // Operations
  public:
    Relation ();
    Relation (std::string strJson);
    ~Relation ();
    bool checkConsistency ();
    void debug ();
    bool isBetween (std::string characterA, std::string characterB);
    relType getType ();
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
