// Generated by dia2code
#ifndef STATE__RELATION__H
#define STATE__RELATION__H


namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class Relation - 
  class Relation {
    // Attributes
  private:
    IdRef<Character> characterA;
    IdRef<Character> characterB;
    /// enumeration:
1 for non aggression, 2 for alliance, 3 for friendship, 4 for rivalry, 5 for war
    enum type;
    int endTurn;
    // Setters and Getters
  };

};

#endif
