// Generated by dia2code
#ifndef STATE__TITLES__H
#define STATE__TITLES__H

#include <string>
#include <map>
#include <json.hpp>

namespace state {
  class Kingdom;
}

#include "Kingdom.h"

namespace state {

  /// class Titles - 
  class Titles {
    // Associations
    // Attributes
  private:
    std::map<std::string, Kingdom> kingdoms;
    // Operations
  public:
    Titles ();
    Titles (std::string strJson);
    ~Titles ();
    bool checkConsistency ();
    void debug ();
    unsigned int getKingdomColor (std::string kingdomId);
    nlohmann::json fetchKingdomData (std::string kingdomId);
    std::string getKingdomHolder (std::string kingdomId);
    // Setters and Getters
  };

};

#endif
