// Generated by dia2code
#ifndef STATE__TRAIT__H
#define STATE__TRAIT__H

#include <string>

namespace state {

  /// class Trait - 
  class Trait {
    // Attributes
  private:
    std::string id;
    std::string opposedId;
    int diplomacyModifier;
    int stewardshipModifier;
    int martialModifier;
    int intrigueModifier;
    // Operations
  public:
    Trait (std::string id, std::string opposedId, int diplomacyModifier, int stewardshipModifier, int martialModifier, int intrigueModifier);
    Trait (std::string id, std::string path);
    Trait ();
    // Setters and Getters
  };

};

#endif
