// Generated by dia2code
#ifndef STATE__TRAITS__H
#define STATE__TRAITS__H

#include <string>

namespace state {

  /// class Traits - 
  class Traits {
    // Attributes
  private:
    std::string id;
    std::string opposedId;
    int diplomacyModifier;
    int stewardshipModifier;
    int martialModifier;
    int intrigueModifier;
    // Setters and Getters
  };

};

#endif
