// Generated by dia2code
#ifndef STATE__TRAVELORDER__H
#define STATE__TRAVELORDER__H

#include <vector>
#include <string>
#include <json.hpp>

namespace state {
  class OneProvinceOrder;
  class Army;
  class Order;
}

#include "OneProvinceOrder.h"
#include "Order.h"

namespace state {

  /// class TravelOrder - A class representing the orders given by the player
  class TravelOrder : public state::Order {
    // Attributes
  private:
    std::vector<OneProvinceOrder> orderList;
    Army * parent;
    // Operations
  public:
    TravelOrder ();
    TravelOrder (Army * parent, std::string strJson);
    ~TravelOrder ();
    bool checkConsistency ();
    void debug ();
    /// Advances the current step's progression and returns true if a step is cleared
    bool nextStep ();
    unsigned int size ();
    nlohmann::json toJson ();
    // Setters and Getters
  };

};

#endif
