// Generated by dia2code
#ifndef STATE__TRAVELORDER__H
#define STATE__TRAVELORDER__H

#include <vector>

namespace state {
  class OneProvinceOrder;
  class Order;
}

#include "OneProvinceOrder.h"
#include "Order.h"

namespace state {

  /// class TravelOrder - A class representing the orders given by the player
  class TravelOrder : public state::Order {
    // Attributes
  private:
    std::vector<OneProvinceOrder> orderList;
    // Setters and Getters
  };

};

#endif
