// Generated by dia2code
#ifndef STATE__WAR__H
#define STATE__WAR__H

#include <string>
#include <vector>
#include <json.hpp>

namespace state {

  /// class War - 
  class War {
    // Attributes
  private:
    std::string id;
    std::string targetTitle;
    std::vector<std::string> attackerCamp;
    std::vector<std::string> defenderCamp;
    /// 100: attacker victory, -100 defender victory
    int warScore;
    // Operations
  public:
    War ();
    War (std::string strJson);
    ~War ();
    void debug ();
    nlohmann::json toJson ();
    std::string getId ();
    int getScore ();
    // Setters and Getters
  };

};

#endif
