// Generated by dia2code
#ifndef STATE__WAR__H
#define STATE__WAR__H

#include <string>
#include <vector>
#include <json.hpp>

namespace state {

  /// class War - 
  class War {
    // Attributes
  private:
    std::string id;
    std::string targetProvince;
    std::string claimantCharacter;
    std::string mainDefender;
    std::vector<std::string> attackerCamp;
    std::vector<std::string> defenderCamp;
    /// 100: attacker victory, -100 defender victory
    int warScore;
    // Operations
  public:
    War ();
    War (std::string strJson);
    ~War ();
    void debug ();
    nlohmann::json toJson ();
    std::string getId ();
    std::string getTargetTitle ();
    int getScore ();
    std::string getClaimantCharacter ();
    std::string getDefendingCharacter ();
    std::vector<std::string> getAttackerCamp ();
    std::vector<std::string> getDefenderCamp ();
    void setScore (int score);
    bool attackerWon ();
    bool defenderWon ();
    // Setters and Getters
  };

};

#endif
