// Generated by dia2code
#ifndef RENDER__ARMY__H
#define RENDER__ARMY__H


namespace render {
  class Army;
  class DynamicContent;
}

#include "DynamicContent.h"

namespace render {

  /// class Army - 
  class Army : public render::DynamicContent {
    // Attributes
  public:
    Province province;
    // Operations
  public:
    Army ();
    getInfo (Army army);
    draw ();
    // Setters and Getters
  };

};

#endif
