// Generated by dia2code
#ifndef RENDER__BUTTON__H
#define RENDER__BUTTON__H


namespace render {

  /// class Button - 
  class Button {
    // Attributes
  public:
    bool available;
    pair<int x, int y> position;
    pair<int height, int width> size;
    // Operations
  public:
    press ();
    Button ();
    Button (pair<int x, int y> position);
    // Setters and Getters
  };

};

#endif
