// Generated by dia2code
#ifndef RENDER__BUTTON__H
#define RENDER__BUTTON__H

#include <string>

namespace render {
  class InteractiveElement;
}

#include "InteractiveElement.h"

namespace render {

  /// class Button - 
  class Button : public render::InteractiveElement {
    // Attributes
  private:
    bool available;
    std::string text;
    // Operations
  public:
    press ();
    Button ();
    Button (function function, std::string text, int width, int height, int x, int y);
    // Setters and Getters
  };

};

#endif
