// Generated by dia2code
#ifndef RENDER__CANVAS__H
#define RENDER__CANVAS__H


namespace render {
  class Window;
  class IObserver;
  class Cadre;
  class DynamicContent;
}

#include "Window.h"
#include "IObserver.h"
#include "Cadre.h"
#include "DynamicContent.h"

namespace render {

  /// class Canvas - 
  class Canvas {
    // Associations
    // Attributes
  public:
    pair<int height,int width> size;
    // Operations
  public:
    Canvas ();
    Canvas (Window window);
    Canvas (pair<int height, int width> size);
    Canvas (Window window, pair<int height, int width> size);
    // Setters and Getters
  };

};

#endif
