// Generated by dia2code
#ifndef RENDER__CHARACTERDATA__H
#define RENDER__CHARACTERDATA__H


namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class CharacterData - 
  class CharacterData : public render::Element {
    // Operations
  public:
    CharacterData ();
    ~CharacterData ();
    void draw ();
    // Setters and Getters
  };

};

#endif
