// Generated by dia2code
#ifndef RENDER__COLORMAP__H
#define RENDER__COLORMAP__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Image;
}


namespace render {

  /// class ColorMap - 
  class ColorMap {
    // Attributes
  private:
    sf::Image image;
    // Operations
  public:
    ColorMap ();
    ColorMap (std::string path);
    ~ColorMap ();
    unsigned int getPixel (int x, int y);
    // Setters and Getters
  };

};

#endif
