// Generated by dia2code
#ifndef RENDER__DATA__H
#define RENDER__DATA__H

#include <SFML/Graphics.hpp>
#include <string>
#include <vector>

namespace render {
  class Button;
  class ToState;
  class ToEngine;
  class Render;
  class Element;
}

#include "Element.h"
#include "ToEngine.h"
#include "ToState.h"
#include "Button.h"

namespace render {

  /// class Data - 
  class Data : public render::Element {
    // Associations
    // Attributes
  public:
    enum Types{Character=0,Relations=1, Province=2, Army=3};
  private:
    sf::Text text;
    sf::Font font;
    std::string data;
    sf::RectangleShape frame;
    sf::View view;
    std::vector<Button *> buttons;
    Types type;
    ToState * state;
    ToEngine * engine;
    std::string id;
    // Operations
  public:
    Data ();
    Data (Render * mainRender, ToState * state, ToEngine * engine);
    ~Data ();
    void draw ();
    void select (Types type, std::string data);
    bool contains (int x, int y);
    void click (int x, int y);
    void scroll (int deltaY);
    void handleButtons (std::string button);
    // Setters and Getters
  };

};

#endif
