// Generated by dia2code
#ifndef RENDER__DYNAMICCONTENT__H
#define RENDER__DYNAMICCONTENT__H


namespace render {

  /// class DynamicContent - 
  class DynamicContent {
    // Attributes
  public:
     canvas : Canvas;
    // Operations
  public:
    draw ();
    getInfo ();
    // Setters and Getters
  };

};

#endif
