// Generated by dia2code
#ifndef RENDER__ELEMENT__H
#define RENDER__ELEMENT__H


namespace render {
  class Render;
}

namespace render {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    Render * render;
    int width;
    int height;
    int x;
    int y;
    // Operations
  public:
    virtual void draw ();
    // Setters and Getters
    const Render *& getRender() const;
    void setRender(const Render *& render);
    int getWidth() const;
    void setWidth(int width);
    int getHeight() const;
    void setHeight(int height);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
