// Generated by dia2code
#ifndef RENDER__ELEMENT__H
#define RENDER__ELEMENT__H


namespace render {
  class Frame;
}

#include "Frame.h"

namespace render {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    Frame * frame;
    int width;
    int height;
    int x;
    static int y;
    // Setters and Getters
    const Frame *& getFrame() const;
    void setFrame(const Frame *& frame);
    int getWidth() const;
    void setWidth(int width);
    int getHeight() const;
    void setHeight(int height);
    int getX() const;
    void setX(int x);
  };

};

#endif
