// Generated by dia2code
#ifndef RENDER__FRAME__H
#define RENDER__FRAME__H


namespace render {
  class Canvas;
  class Element;
}

#include "Canvas.h"
#include "Element.h"

namespace render {

  /// class Frame - 
  class Frame {
    // Associations
    // Attributes
  private:
    Canvas canvas;
    int x;
    int y;
    int width;
    int height;
    // Operations
  public:
    Frame ();
    Frame (Canvas canvas);
    Frame (Canvas canvas, int width, int height);
    Frame (Canvas canvas, int width, int height, int x, int y);
    ~Frame ();
    int getWidth ();
    int getHeight ();
    int getX ();
    int getY ();
    // Setters and Getters
  };

};

#endif
