// Generated by dia2code
#ifndef RENDER__IMAGE__H
#define RENDER__IMAGE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class Frame;
  class Element;
}

#include "Element.h"

namespace render {

  /// class Image - 
  class Image : public render::Element {
    // Attributes
  private:
    bool keepRatio;
    bool followWidth;
    sf::Sprite sprite;
    sf::Texture texture;
    // Operations
  public:
    Image ();
    Image (Frame* frame);
    Image (Frame* frame, int width, int height);
    Image (Frame* frame, int width, int height, int x, int y);
    Image (Frame* frame, int width, int height, int x, int y, bool keepRatio, bool followWidth);
    void importFile (std::string path);
    sf::Sprite getSprite ();
    // Setters and Getters
  };

};

#endif
