// Generated by dia2code
#ifndef RENDER__INTERACTIVEELEMENT__H
#define RENDER__INTERACTIVEELEMENT__H


namespace render {
  class Element;
  class IObserver;
}

#include "Element.h"
#include "IObserver.h"

namespace render {

  /// class InteractiveElement - 
  class InteractiveElement : public render::Element {
    // Associations
    // Setters and Getters
  };

};

#endif
