// Generated by dia2code
#ifndef RENDER__IOBSERVER__H
#define RENDER__IOBSERVER__H


namespace render {

  // Interface
  /// class IObserver - 
  class IObserver {
    // Operations
  public:
    virtual void somethingHappens () = default;
    // Setters and Getters
  };

};

#endif
