// Generated by dia2code
#ifndef RENDER__MAP__H
#define RENDER__MAP__H


namespace render {
  class Map;
  class DynamicContent;
}

#include "DynamicContent.h"

namespace render {

  /// class Map - 
  class Map : public render::DynamicContent {
    // Attributes
  public:
    pair<int x, int y> position;
    int zoom;
    // Operations
  public:
    Map ();
    void changeZoom (int var);
    getInfo (Map map);
    draw ();
    moveView (pair<int varx, int vary> direction);
    // Setters and Getters
  };

};

#endif
