// Generated by dia2code
#ifndef RENDER__OBSERVERMAP__H
#define RENDER__OBSERVERMAP__H


namespace render {
  class IObserver;
}

#include "IObserver.h"

namespace render {

  /// class ObserverMap - 
  class ObserverMap : public render::IObserver {
    // Operations
  public:
    somethingHappens() ();
    // Setters and Getters
  };

};

#endif
