// Generated by dia2code
#ifndef RENDER__OBSERVERBUTTON__H
#define RENDER__OBSERVERBUTTON__H


namespace render {
  class IObserver;
}

#include "IObserver.h"

namespace render {

  /// class ObserverButton - 
  class ObserverButton : public render::IObserver {
    // Operations
  public:
    void somethingHappens ();
    // Setters and Getters
  };

};

#endif
