// Generated by dia2code
#ifndef RENDER__OBSERVERARMY__H
#define RENDER__OBSERVERARMY__H


namespace render {
  class IObserver;
}

#include "IObserver.h"

namespace render {

  /// class ObserverArmy - 
  class ObserverArmy : public render::IObserver {
    // Operations
  public:
    void somethingHappens ();
    // Setters and Getters
  };

};

#endif
