// Generated by dia2code
#ifndef RENDER__PLAYERDATA__H
#define RENDER__PLAYERDATA__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class ToState;
  class Render;
  class Element;
}

#include "Element.h"
#include "ToState.h"

namespace render {

  /// class PlayerData - 
  class PlayerData : public render::Element {
    // Associations
    // Attributes
  public:
    ToState * state;
  private:
    sf::Text text;
    sf::Font font;
    std::string data;
    sf::RectangleShape frame;
    std::string id;
    // Operations
  public:
    PlayerData ();
    PlayerData (Render * mainRender, ToState * state);
    ~PlayerData ();
    void draw ();
    void selectCharacter (std::string id);
    // Setters and Getters
  };

};

#endif
