// Generated by dia2code
#ifndef RENDER__POPUPS__H
#define RENDER__POPUPS__H

#include <string>
#include <map>

namespace render {
  class Render;
  class ToState;
  class ToEngine;
  class PopUp;
}

#include "ToState.h"
#include "ToEngine.h"
#include "PopUp.h"

namespace render {

  /// class PopUps - 
  class PopUps {
    // Associations
    // Attributes
  private:
    std::map<std::string, PopUp*> popUps;
    Render * mainRender;
    ToState * state;
    ToEngine * engine;
    std::string playerId;
    // Operations
  public:
    PopUps (Render * mainRender, ToState * state, ToEngine * engine, std::string playerId);
    ~PopUps ( );
    void newPopUp (bool requireAnswer, PopUp::Action action, std::string causeId, std::string targetId, std::string id, std::string data);
    void deletePopUp (std::string id);
    void update ();
    void draw ();
    bool contains (int x, int y);
    void click (int x, int y);
    void move (int x, int y);
    void release ();
    // Setters and Getters
  };

};

#endif
