// Generated by dia2code
#ifndef RENDER__POPUP__H
#define RENDER__POPUP__H

#include <SFML/Graphics.hpp>
#include <vector>
#include <string>

namespace render {
  class Button;
  class ToState;
  class ToEngine;
  class Render;
  class Element;
}

#include "Element.h"

namespace render {

  /// class PopUp - 
  class PopUp : public render::Element {
    // Attributes
  public:
    bool requiresAnswer;
    enum Type{War=0,Peace=1,Alliance=2,Claim=3,Plot=4,Surr=5,Other=6};
    int clickX;
    int clickY;
    bool selected     = false;
  private:
    sf::RectangleShape frame;
    sf::Text text;
    sf::Font font;
    std::vector<Button*> buttons;
    std::string causeId;
    ToState * state;
    ToEngine * engine;
    std::string data;
    std::string messageId;
    // Operations
  public:
    PopUp (Render * mainRender, bool requiresAnswer, Type type, std::string causeId, ToState * state, ToEngine * engine, std::string data, std::string messageId);
    ~PopUp ();
    void select (bool requiresAnswer, Type type, std::string causeId, std::string data);
    void draw ();
    bool contains (int x, int y);
    bool click (int x, int y);
    void handleButtons (std::string button);
    void move (int x, int y);
    void deselect ();
    bool isSelected ();
    // Setters and Getters
  };

};

#endif
