// Generated by dia2code
#ifndef RENDER__PROVINCEDATA__H
#define RENDER__PROVINCEDATA__H


namespace render {
  class Element;
}

#include "Element.h"

namespace render {

  /// class ProvinceData - 
  class ProvinceData : public render::Element {
    // Operations
  public:
    ProvinceData ();
    ~ProvinceData ();
    // Setters and Getters
  };

};

#endif
