// Generated by dia2code
#ifndef RENDER__SHOWARMY__H
#define RENDER__SHOWARMY__H


namespace state {
  class Army;
};
namespace render {
  class Image;
}

#include "Image.h"
#include "state/Army.h"

namespace render {

  /// class ShowArmy - 
  class ShowArmy {
    // Associations
    // Attributes
  private:
    state::Army * army;
    Image imageArmy;
    // Operations
  public:
    ShowArmy ();
    ShowArmy (state::Army * army);
    ~ShowArmy ();
    // Setters and Getters
  };

};

#endif
