// Generated by dia2code
#ifndef RENDER__SHOWARMIES__H
#define RENDER__SHOWARMIES__H

#include <vector>

namespace render {
  class ShowArmy;
}

#include "ShowArmy.h"

namespace render {

  /// class ShowArmies - 
  class ShowArmies {
    // Associations
    // Attributes
  private:
    std::vector<ShowArmy> armies;
    // Operations
  public:
    ShowArmies ();
    ~ShowArmies ();
    void addArmy (ShowArmy showArmy);
    std::vector<ShowArmy> * getArmies ();
    // Setters and Getters
  };

};

#endif
