// Generated by dia2code
#ifndef RENDER__TEXT__H
#define RENDER__TEXT__H


namespace render {

  /// class Text - 
  class Text {
    // Attributes
  public:
    pair<int x, int y> position;
    pair<int height, int width> size;
    // Setters and Getters
  };

};

#endif
