// Generated by dia2code
#ifndef RENDER__TOENGINE__H
#define RENDER__TOENGINE__H

#include <string>
#include <queue>
#include <queue>

namespace render {

  /// class ToEngine - 
  class ToEngine {
    // Attributes
  public:
    std::queue<std::string> * commands;
    // Operations
  public:
    ToEngine ();
    ToEngine (std::queue<std::string> * commands);
    ~ToEngine ();
    void addCommand (std::string idTarget, std::string command);
    // Setters and Getters
  };

};

#endif
