// Generated by dia2code
#ifndef RENDER__TOENGINE__H
#define RENDER__TOENGINE__H

#include <engine.h>
#include <string>

namespace render {

  /// class ToEngine - 
  class ToEngine {
    // Attributes
  public:
    engine::EngineCore * engine;
    // Operations
  public:
    ToEngine ();
    ToEngine (engine::EngineCore * engine);
    ~ToEngine ();
    void addCommand (std::string idTarget, std::string command);
    // Setters and Getters
  };

};

#endif
