// Generated by dia2code
#ifndef RENDER__TOSTATE__H
#define RENDER__TOSTATE__H

#include <state.h>
#include <string>
#include <map>

namespace state {
  class GameState;
}

#include "state/GameState.h"

namespace render {

  /// class ToState - 
  class ToState {
    // Associations
    // Attributes
  public:
    state::GameState * state;
    std::map<std::string, std::string> mapColorId;
    // Operations
  public:
    ToState ();
    ToState (state::GameState * state);
    ~ToState ();
    std::string fetchCharacterData (std::string id);
    std::string fetchProvinceData (std::string colorCode);
    std::string fetchArmyData (std::string id);
    std::string fetchAllArmiesData ();
    std::string fetchAllRelationsData ();
    std::string fetchAllPlayersData ();
    std::string fetchAllProvincesData ();
    std::string fetchCharacterDataFromColor (std::string colorCode);
    // Setters and Getters
  };

};

#endif
