// Generated by dia2code
#ifndef RENDER__TOSTATE__H
#define RENDER__TOSTATE__H

#include <state.h>
#include <json.hpp>
#include <string>

namespace state {
  class GameState;
}

#include "state/GameState.h"

namespace render {

  /// class ToState - 
  class ToState {
    // Associations
    // Attributes
  public:
    state::GameState * state;
    // Operations
  public:
    ToState ();
    ToState (state::GameState * state);
    ~ToState ();
    nlohmann::json fetchCharacterData (std::string id);
    nlohmann::json fetchProvinceData (std::string id);
    nlohmann::json fetchArmyData (std::string id);
    nlohmann::json fetchAllArmiesData ();
    nlohmann::json fetchAllRelationsData ();
    nlohmann::json fetchAllPlayersData ();
    nlohmann::json fetchAllProvincesData ();
    nlohmann::json fetchCharacterDataFromColor (std::string colorCode);
    nlohmann::json fetchProvinceDataFromColor (std::string colorCode);
    nlohmann::json fetchAllProvincesKingdomColor ();
    nlohmann::json fetchKingdomData (std::string id);
    nlohmann::json fetchPlayerMessagesData (std::string playerId);
    std::string getCurrentPlayer ();
    std::string getCharacterOfPlayer (std::string playerId);
    std::string getCurrentPlayerCharacter ();
    // Setters and Getters
  };

};

#endif
