// Generated by dia2code
#ifndef RENDER__VIEWMAP__H
#define RENDER__VIEWMAP__H

#include <string>

namespace render {
  class Image;
  class ShowArmies;
  class Render;
  class Element;
}

#include "Image.h"
#include "ShowArmies.h"
#include "Element.h"

namespace render {

  /// class ViewMap - 
  class ViewMap : public render::Element {
    // Associations
    // Attributes
  private:
    Image map;
    sf::View view;
    ShowArmies showArmies;
    // Operations
  public:
    ViewMap ();
    ViewMap (Render * render, Image map, ShowArmies& showArmies);
    ViewMap (Render * render, Image map, sf::Vector2f size, sf::Vector2f center, ShowArmies& showArmies);
    ~ViewMap ();
    sf::Vector2f getSize ();
    void changeZoom (float zoom);
    sf::Vector2f getCenter ();
    void moveView (float deltaX, float deltaY);
    void draw ();
    sf::View * getView ();
    bool contains (int x, int y);
    std::string leftClick (sf::Vector2f pixel);
    std::string rightClick (sf::Vector2f pixel);
    void checkZoomY (float zoom);
    // Setters and Getters
  };

};

#endif
