// Generated by dia2code
#ifndef RENDER__VIEWMAP__H
#define RENDER__VIEWMAP__H


namespace render {
  class Image;
};
namespace sf {
  class View;
};
namespace render {
  class Render;
  class Element;
}

#include "Image.h"
#include "Element.h"

namespace render {

  /// class ViewMap - 
  class ViewMap : public render::Element {
    // Associations
    // Attributes
  private:
    Image map;
    sf::Vector2f center;
    sf::Vector2f size;
    sf::View view;
    // Operations
  public:
    ViewMap ();
    ViewMap (Render * render, Image map);
    ViewMap (Render * render, Image map, sf::Vector2f size, sf::Vector2f center);
    ~ViewMap ();
    void changeSize (int var);
    void moveView (int deltaX, int deltaY);
    void draw ();
    // Setters and Getters
  };

};

#endif
