// Generated by dia2code
#ifndef RENDER__WINDOW__H
#define RENDER__WINDOW__H

#include <SFML/Graphics.hpp>

namespace render {
  class Canvas;
}

#include "Canvas.h"

namespace render {

  /// class Window - 
  class Window {
    // Associations
    // Attributes
  private:
    int width;
    int height;
    sf::RenderWindow window;
    // Operations
  public:
    Window ();
    Window (int width, int height);
    void renderLoop ();
    int getWidth ();
    int getHeight ();
    // Setters and Getters
  };

};

#endif
