// Generated by dia2code
#ifndef RENDER__WINDOW__H
#define RENDER__WINDOW__H


namespace render {
  class Canvas;
}

#include "Canvas.h"

namespace render {

  /// class Window - 
  class Window {
    // Associations
    // Attributes
  public:
    pair<int height, int width> size;
    // Operations
  public:
    Window ();
    Window (pair<int height, int width> size);
    renderLoop ();
    // Setters and Getters
  };

};

#endif
