// Generated by dia2code
#ifndef AI__BASICAI__H
#define AI__BASICAI__H

#include <render.h>
#include <string>
#include <map>
#include <state.h>
#include <engine.h>

namespace ai {

  /// class BasicAI - somewhat advanced ai
  class BasicAI {
    // Attributes
  private:
    render::ToState toState;
    render::ToEngine toEngine;
    std::map<std::pair<std::string, std::string>, float> scores;
    std::string playerId;
    std::string characterId;
    // Operations
  public:
    BasicAI (state::GameState * state, engine::EngineCore * engine, std::string playerId);
    ~BasicAI ();
    void calculateScores ();
    void chooseAction ();
    // Setters and Getters
  };

};

#endif
