// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <render.h>
#include <state.h>
#include <engine.h>

namespace ai {

  /// class RandomAI - 
  class RandomAI {
    // Attributes
  private:
    render::ToState toState;
    render::ToEngine toEngine;
    // Operations
  public:
    RandomAI (state::GameState * state, engine::EngineCore * engine);
    ~RandomAI ();
    void randomActions ();
    // Setters and Getters
  };

};

#endif
