// Generated by dia2code
#ifndef AI__SCORENODE__H
#define AI__SCORENODE__H

#include <vector>

namespace ai {
  class ScoreNode;
};
namespace engine {
  class Command;
}

#include "engine/Command.h"

namespace ai {

  /// class ScoreNode - 
  class ScoreNode {
    // Associations
    // Attributes
  private:
    ScoreNode * parent;
    std::vector<ScoreNode*> children;
    int score;
    std::vector<engine::Command> commands;
    // Operations
  public:
    ScoreNode ();
    ~ScoreNode ();
    void setScore (int score);
    int getScore ();
    void setCommands (std::vector<engine::Command> commands);
    std::vector<engine::Command> getCommands ();
    void setParent (ScoreNode * parent);
    ScoreNode * getParent ();
    void addChild (ScoreNode * child);
    void clearChildren ();
    std::vector<ScoreNode*> getChildren ();
    // Setters and Getters
  };

};

#endif
