// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <string>

namespace engine {

  /// class Command - 
  class Command {
    // Attributes
  public:
    /// Possible types of command
    enum commandType{moveArmy = 0, ActionButton = 1, TurnButton = 2};
  private:
    /// Type of command
    commandType type;
    /// Additional data for this command (type of button, etc)
    std::string argument;
    // Operations
  public:
    Command ();
    Command (commandType type, std::string argument);
    ~Command ();
    commandType getType ();
    std::string getArgument ();
    // Setters and Getters
  };

};

#endif
