// Generated by dia2code
#ifndef ENGINE__ENGINECORE__H
#define ENGINE__ENGINECORE__H

#include <queue>
#include <state.h>
#include <string>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class EngineCore - 
  class EngineCore {
    // Associations
    // Attributes
  public:
    std::queue<Command> * commands;
    state::GameState * gameState;
    // Operations
  public:
    EngineCore ();
    EngineCore (state::GameState * gameState);
    EngineCore (state::GameState * gameState, std::queue<Command> * events);
    ~EngineCore ();
    int mainLoop ();
    void pushCommand (Command command);
    void processCommand (Command command);
    void endWar (std::string warId, std::string winner);
    void turnButton ();
    void endTurn ();
    // Setters and Getters
  };

};

#endif
