// Generated by dia2code
#ifndef ENGINE__ENGINEEVENT__H
#define ENGINE__ENGINEEVENT__H

#include <string>
#include <json.hpp>

namespace engine {

  /// class EngineEvent - 
  class EngineEvent {
    // Attributes
  public:
    enum eventType{ClickArmy = 0, RClickProv = 1, LClickProv = 2, ClickButton = 3};
  private:
    eventType type;
    std::string argument;
    nlohmann::json test;
    // Operations
  public:
    EngineEvent ();
    EngineEvent (eventType type, std::string argument);
    ~EngineEvent ();
    // Setters and Getters
  };

};

#endif
