// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/IObserver.h"
#include "render/Image.h"
#include "render/Text.h"
#include "render/Button.h"
#include "render/Cadre.h"
#include "render/DynamicContent.h"
#include "render/Canvas.h"
#include "render/Window.h"
#include "render/Render.h"
#include "render/Army.h"
#include "render/Map.h"
#include "render/ObserverMap.h"
#include "render/ObserverArmy.h"
#include "render/ObserverButton.h"
#endif
